global_frame: map # sometimes '/map' works but in documentation, it says that '/map' is discontinued in noetic. Use 'map'
rolling_window: true
track_unknown_space: false # false so that it traverses unknown space freely as if there is no obstacle

plugins:
  - {name: static,                  type: "costmap_2d::StaticLayer"}
  - {name: inflation,               type: "costmap_2d::InflationLayer"}

update_frequency: 10.0
width: 200
height: 200