footprint: [[-0.5, -0.5], [-0.5, 0.5], [0.5, 0.5], [0.5, -0.5]]
footprint_padding: 0.01

robot_base_frame: base_link
update_frequency: 2.0 # default 0.2
publish_frequency: 2.0
transform_tolerance: 0.5

resolution: 0.05

obstacle_range: 5.5
raytrace_range: 6.0

#layer definitions
static:
    map_topic: /map
    subscribe_to_updates: true

obstacles_laser:
    observation_sources: point_cloud_sensor
    point_cloud_sensor: {sensor_frame: lidar_link, data_type: PointCloud2, topic: /ouster/points, marking: true, clearing: true} # lidar topic

inflation:
    inflation_radius: 1.0

