controller_frequency: 2 # Rate in Hz

v_min: -2.0
v_max: 2.0
w_min: -1.0
w_max: 1.0

max_accel_lin: 1.0
max_accel_ang: 0.2
dt: 0.1     # time step for simulation
sim_time: 2 # simulation time in sec (Time horizon)    
num_samples_v: 5
num_samples_w: 5

# Cost function weights

w_heading: 1 # Weight for heading to goal
w_dist: 1 # Weight for distance to goal
w_lin: 1 # Weight for linear velocity (keep it as high as possible)
w_ang: 1 # Weight for angular velocity (keep it average)
w_obs: 1 # Weight for obstacle avoidance # NOT USING THIS YET

# Robot Footprint
robot_width: 0.75
robot_length: 0.75
robot_height: 0.75
robot_grid_n: 10

# Obstacle avoidance parameters
min_z: 0.3 # Minimum height to consider obstacles
max_z: 1.5 # Maximum height to consider obstacles

# Goal Tolerance Parameters
xy_goal_tolerance: 0.2 # Distance to goal to consider it reached (in meters)

# NOT USING THIS YET
obstacle_threshold: 0.75 # Distance to obstacle to start avoiding it (in meters) - used in the cost function