controller_frequency: 10 # Rate in Hz

v_min: -0.5
v_max: 0.5
w_min: -0.75
w_max: 0.75

max_accel_lin: 2.0
max_accel_ang: 2.0
dt: 0.1     # time step for simulation
sim_time: 2 # simulation time in sec (Time horizon)    
num_samples_v: 10
num_samples_w: 10

# Cost function weights

w_heading: 1 # Weight for heading to goal
w_dist: 0.1 # Weight for distance to goal
w_lin: 1 # Weight for linear velocity (keep it as high as possible)
w_ang: 1 # Weight for angular velocity (keep it average)
w_obs_height: 10 # Weight for obstacle height

w_obs: 1 # Weight for obstacle avoidance # NOT USING THIS YET

# Robot Footprint
robot_width: 1.0
robot_length: 1.0
robot_height: 1.0
robot_grid_n: 10

# Obstacle avoidance parameters
min_z: 0.3 # Minimum height to consider obstacles
max_z: 1.5 # Maximum height to consider obstacles

# Goal Tolerance Parameters
xy_goal_tolerance: 0.2 # Distance to goal to consider it reached (in meters)

# NOT USING THIS YET
obstacle_threshold: 0.75 # Distance to obstacle to start avoiding it (in meters) - used in the cost function