global_frame: map # sometimes '/map' works but in documentation, it says that '/map' is discontinued in noetic. Use 'map'
rolling_window: true
track_unknown_space: true # false so that it traverses unknown space freely as if there is no obstacle

plugins:
  - {name: static,                  type: "costmap_2d::StaticLayer"}
  - {name: inflation,               type: "costmap_2d::InflationLayer"}

update_frequency: 2.0
width: 200
height: 200



# global_costmap:
#   global_frame: world
#   robot_base_frame: base_link
#   update_frequency: 5.0
#   static_map: false
#   rolling_window: true
#   width: 6.0
#   height: 6.0
#   resolution: 0.05