controller_frequency: 5 # default: 5
recovery_behaviour_enabled: false

NavfnROS:
  allow_unknown: true # default: true # Specifies whether or not to allow navfn to create plans that traverse unknown space.
  # if you are using layered costmaps with voxel or obstacle layer, you must also set track_unknown_space param to true
  # otherwise it will convert all unknown space to free space and happily go through it.
  default_tolerance: 0.8 # A tolerance on the goal point for the planner.
  # planner_window_x: 100.0 # default: 0.0
  # planner_window_y: 100.0 # default: 0.0

DWAPlannerROS:
  # Robot configuration parameters  
  acc_lim_x: 2.5 # 0.5 # default: 5
  acc_lim_y: 0.0 # default: 0
  acc_lim_th: 1.9 # 0.32 # default: 3.2

  max_vel_x: 3.5 # 0.7 # default: 6.0
  min_vel_x: 2.0 # 0.4 # default: 0.0
  # the simuation rover does not move in y direction
  max_vel_y: 0.0 # default: 0.0
  min_vel_y: 0.0 # default: 0.0

  max_vel_trans: 3.5 # 0.7 # default: 0.5
  min_vel_trans: 2.0 # 0.4 # default: 0.1
  max_vel_rot: 3.5 # 0.7
  min_vel_rot: 2.0 # 0.4

  # Goal Tolerance Parameters
  yaw_goal_tolerance: 0.2
  xy_goal_tolerance: 0.2
  latch_xy_goal_tolerance: false

  # # Forward Simulation Parameters
  sim_time: 2.0
  prune_plan: false
  # sim_granularity: 0.02
  # vx_samples: 6
  # vy_samples: 0
  # vtheta_samples: 20
  # penalize_negative_x: true

  # # Trajectory scoring parameters
  # path_distance_bias: 32.0 # The weighting for how much the controller should stay close to the path it was given
  # goal_distance_bias: 24.0 # The weighting for how much the controller should attempt to reach its local goal, also controls speed
  occdist_scale: 0.005 # The weighting for how much the controller should attempt to avoid obstacles
  # forward_point_distance: 0.325 # The distance from the center point of the robot to place an additional scoring point, in meters
  # stop_time_buffer: 0.2  # The amount of time that the robot must stThe absolute value of the veolicty at which to start scaling the robot's footprint, in m/sop before a collision in order for a trajectory to be considered valid in seconds
  # scaling_speed: 0.25 # The absolute value of the veolicty at which to start scaling the robot's footprint, in m/s
  # max_scaling_factor: 0.2 # The maximum factor to scale the robot's footprint by
  publish_cost_grid: true
  # # Oscillation Prevention Parameters
  # oscillation_reset_dist: 0.25 #How far the robot must travel in meters before oscillation flags are reset (double, default: 0.05)



# TrajectoryPlannerROS:
#   # Robot Configuration Parameters
#   acc_lim_x: 0.5
#   acc_lim_theta: 0.32 # defualt: 3.2

#   max_vel_x: 0.5
#   min_vel_x: 0.0 # defualt: 0.0

#   max_vel_theta: 0.1
#   min_vel_theta: -0.1
#   min_in_place_vel_theta: 0.2

#   holonomic_robot: false
#   escape_vel: -0.1

#   # Goal Tolerance Parameters
#   yaw_goal_tolerance: 0.1
#   xy_goal_tolerance: 0.2
#   latch_xy_goal_tolerance: false

#   # Forward Simulation Parameters
#   sim_time: 2.0
#   sim_granularity: 0.02
#   angular_sim_granularity: 0.02
#   vx_samples: 6
#   vtheta_samples: 20
#   controller_frequency: 20 # default: 20

#   # Trajectory scoring parameters
#   meter_scoring: true # Whether the gdist_scale and pdist_scale parameters should assume that goal_distance and path_distance are expressed in units of meters or cells. Cells are assumed by default (false).
#   occdist_scale:  0.01 #The weighting for how much the controller should attempt to avoid obstacles. default 0.01
#   pdist_scale: 0.75  #     The weighting for how much the controller should stay close to the path it was given . default 0.6
#   gdist_scale: 1.0 #     The weighting for how much the controller should attempt to reach its local goal, also controls speed  default 0.8

#   heading_lookahead: 0.325  #How far to look ahead in meters when scoring different in-place-rotation trajectories
#   heading_scoring: false  #Whether to score based on the robot's heading to the path or its distance from the path. default false
#   heading_scoring_timestep: 0.8   #How far to look ahead in time in seconds along the simulated trajectory when using heading scoring (double, default: 0.8)
#   dwa: true #Whether to use the Dynamic Window Approach (DWA)_ or whether to use Trajectory Rollout
#   simple_attractor: false
#   publish_cost_grid_pc: true  

#   # Oscillation Prevention Parameters
#   oscillation_reset_dist: 0.25 #How far the robot must travel in meters before oscillation flags are reset (double, default: 0.05)
#   escape_reset_dist: 0.1
#   escape_reset_theta: 0.1













# TebLocalPlannerROS:

#  odom_topic: /robot_base_velocity_controller/odom
#  map_frame: /odom
    
#  # Trajectory
  
#  teb_autosize: True
#  dt_ref: 0.3
#  dt_hysteresis: 0.1
#  global_plan_overwrite_orientation: True
#  max_global_plan_lookahead_dist: 3.0
#  feasibility_check_no_poses: 5
    
#  # Robot
         
#  max_vel_x: 0.4
#  max_vel_x_backwards: 0.2
#  max_vel_theta: 0.3
#  acc_lim_x: 0.5
#  acc_lim_theta: 0.5
#  min_turning_radius: 0.0
#  footprint_model: # types: "point", "circular", "two_circles", "line", "polygon"
#    type: "circular"
#    radius: 1.0 # for type "circular"
#   #  line_start: [-0.3, 0.0] # for type "line"
#   #  line_end: [0.3, 0.0] # for type "line"
#   #  front_offset: 0.2 # for type "two_circles"
#   #  front_radius: 0.2 # for type "two_circles"
#   #  rear_offset: 0.2 # for type "two_circles"
#   #  rear_radius: 0.2 # for type "two_circles"
#   #  vertices: [ [0.25, -0.05], [0.18, -0.05], [0.18, -0.18], [-0.19, -0.18], [-0.25, 0], [-0.19, 0.18], [0.18, 0.18], [0.18, 0.05], [0.25, 0.05] ] # for type "polygon"

#  # GoalTolerance
    
#  xy_goal_tolerance: 0.2
#  yaw_goal_tolerance: 0.1
#  free_goal_vel: False
    
#  # Obstacles
    
#  min_obstacle_dist: 0.55
#  include_costmap_obstacles: True
#  costmap_obstacles_behind_robot_dist: 1.0
#  obstacle_poses_affected: 30
#  costmap_converter_plugin: ""
#  costmap_converter_spin_thread: True
#  costmap_converter_rate: 5

#  # Optimization
    
#  no_inner_iterations: 5
#  no_outer_iterations: 4
#  optimization_activate: True
#  optimization_verbose: False
#  penalty_epsilon: 0.1
#  weight_max_vel_x: 2
#  weight_max_vel_theta: 1
#  weight_acc_lim_x: 1
#  weight_acc_lim_theta: 1
#  weight_kinematics_nh: 1000
#  weight_kinematics_forward_drive: 1
#  weight_kinematics_turning_radius: 1
#  weight_optimaltime: 1
#  weight_obstacle: 50
#  weight_dynamic_obstacle: 10 # not in use yet
#  alternative_time_cost: False # not in use yet

#  # Homotopy Class Planner

#  enable_homotopy_class_planning: True
#  enable_multithreading: True
#  simple_exploration: False
#  max_number_classes: 4
#  roadmap_graph_no_samples: 15
#  roadmap_graph_area_width: 5
#  h_signature_prescaler: 0.5
#  h_signature_threshold: 0.1
#  obstacle_keypoint_offset: 0.1
#  obstacle_heading_threshold: 0.45
#  visualize_hc_graph: False