# request fields
string coordinates
string type
bool give_priority
---
# response fields
string service_response

# Goal types and corresponding coordinate format 
# gps - '{"lat": X,  "long": Y}'
# light_beacon (provided in odom frame) - '{"x": X, "y": Y, "w": W}'
# radio_beacon - '{"lat": X,  "long": Y}'
# odom - '{"x": X, "y": Y, "w": W}'
# sign - '{"dist": D, "heading": H}'



