#!/bin/bash

# This script is used to setup the rover for manual control
# It will start the necessary nodes and launch files to allow for manual control of the rover
# It also launches the zed camera file on the jetson to allow for visual aid in manual control
# To kill, run the command `tmux kill-session -t manual`

source /opt/ros/humble/setup.bash && source /home/rsx/ros2_ws/install/setup.bash

# roscore&

sleep 1

tmux new-session -d -s manual

tmux new-window -t manual:1 'bash -c "source /home/rsx/ros2_ws/src/rsx-rover/scripts/utils/gen/setup_can.sh && sleep 2 && ros2 launch ros_phoenix falcons.launch.py; exec bash"'
tmux new-window -t manual:2 'bash -c "ros2 run rover drive_sender_node; exec bash"'
# tmux new-window -t manual:3 'bash -c "ros2 launch rover realsense.launch; exec bash"'
# tmux new-window -t manual:4 'bash -c "ros2 launch rover joy.launch; exec bash"'

ssh jetson 'source /opt/ros/noetic/setup.bash && source ~/rover_ws/devel/setup.bash && export ROS_MASTER_URI=http://192.168.0.99:11311 && export ROS_IP=192.168.0.250  && ros2 launch rover zed_odom.py && exit'

# source /home/rsx/rover_ws/src/rsx-rover/scripts/utils/gen/setup_can.sh && sleep 2 && roslaunch rover falcons.launch; exec bash
# rosrun rover drive_sender_node; exec bash
# roslaunch rover joy.launch; exec bash